# Pesos para modalidades de Ensino Fundamental
PESO_FUNDAMENTAL_INICIAL = 1.0
PESO_FUNDAMENTAL_FINAL = 1.10
PESO_FUNDAMENTAL_INTEGRAL = 1.40
PESO_ESPECIAL_FUNDAMENTAL_REGULAR = 1.0
PESO_ESPECIAL_FUNDAMENTAL_INTEGRAL = 1.40

# Pesos para modalidades de Ensino Médio
PESO_PROFISSIONALIZANTE = 1.30
PESO_ALTERNANCIA = 1.40
PESO_MEDIO_INTEGRAL = 1.40
PESO_MEDIO_REGULAR = 1.25
PESO_ESPECIAL_MEDIO_PARCIAL = 1.25
PESO_ESPECIAL_MEDIO_INTEGRAL = 1.40

# Multiplicadores especiais
MULTIPLICADOR_ALTERNANCIA = 4.0
MULTIPLICADOR_ESPECIAL = 2.0

# VALORES FIXOS
VALOR_FIXO_GESTAO = 2000.00
VALOR_FIXO_SALA_RECURSO = 2000.00
VALOR_PER_CAPITA_MERENDA = 35.0
VALOR_UNITARIO_KIT_ESCOLAR = 150.0
VALOR_UNITARIO_UNIFORME = 60.0
VALOR_UNITARIO_PERMANENTE = 110.0
VALOR_UNITARIO_PREUNI = 90.0
#VALOR_UNITARIO_CLIMATIZACAO = 0.0 # Desativado temporariamente
VALOR_UNITARIO_SALA_RECURSO = 180.0

# MULTIPLICADORES DE CÁLCULOS
MULTIPLICADOR_GESTAO = 90.0
MULTIPLICADOR_MERENDA_INTEGRAL = 2.0
MULTIPLICADOR_MERENDA_ALTERNANCIA = 4.0
MULTIPLICADOR_INDIGENA_QUILOMBOLA = 2.0

BONUS_REPASSE_POR_AREA_VALORES = (10000, 15000)

# PROJETOS
LIMITE_ALUNOS_PROJETO_1 = 500
LIMITE_ALUNOS_PROJETO_2 = 1000
MULTIPLICADOR_PROJETO_INTEGRAL = 2
NUM_PROJETOS_ATE_500 = 1
NUM_PROJETOS_ATE_1000 = 2
NUM_PROJETOS_ACIMA_1000 = 3
VALOR_PROJETO_UNITARIO = 5000.0

# CONFIGURAÇÕES DE PARCELAS
NUMERO_PARCELAS_PADRAO = 2
PORCENTAGEM_TOTAL = 100.0
